export const AWS_ENUM = {
  AWS_EC2_STATE_CODE_PENDING: 0,
  AWS_EC2_STATE_CODE_RUNNING: 16,
  AWS_EC2_STATE_CODE_TERMINATED: 48,
  AWS_EC2_STATE_CODE_SHUTTING_DOWN: 32,
  AWS_EC2_STATE_CODE_STOPPED: 80,
};
